In [ ]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
import math
import tensorflow as tf
from tensorflow.python.framework import ops
from PIL import Image
from numpy import asarray
import numpy as np
import os
import pandas as pd
import warnings

from keras import layers
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.preprocessing import image
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
import pydot
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
#from resnets_utils import *
from keras.initializers import glorot_uniform
import scipy.misc

import keras.backend as K
K.set_image_data_format('channels_last')
K.set_learning_phase(1)
warnings.filterwarnings("ignore",category=DeprecationWarning)

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)

In [2]:
path1 = r'C:\Users\Aishwarya\Documents\GitHub\Emergency-Vehicle-Recognition\Python Notebook\Data\train\train_images'

image = Image.open(path1 + r'\706.jpg')
data = asarray(image)

In [3]:
data.shape

(224, 224, 3)

In [4]:
a = np.zeros((1646,224,224,3))

a[0,:,:,:] = data

print(a.shape)

(1646, 224, 224, 3)


In [5]:
a[0].shape

(224, 224, 3)

In [6]:
a = np.zeros((1646,224,224,3))

path1 = r'C:\Users\Aishwarya\Documents\GitHub\Emergency-Vehicle-Recognition\Python Notebook\Data\train\train_images'

dir = os.listdir(path1) # original directory with all images  
counter = 0
count2 = 0
all_image_names = []
for i in dir:
    all_image_names.append(int(i.split('.')[0]))

all_image_names = sorted(all_image_names)
    

for i in all_image_names: 
    
    
    image = Image.open(path1 + r'\\'+ str(i) + '.jpg')
    data = asarray(image)
    #print(i)
    a[counter,:,:,:] = data
    
    data = 0
    counter += 1
    


In [7]:
print(a)

[[[[115. 134. 141.]
   [116. 135. 142.]
   [116. 135. 142.]
   ...
   [ 70.  81.  87.]
   [ 74.  85.  91.]
   [ 82.  93.  99.]]

  [[115. 134. 141.]
   [116. 135. 142.]
   [116. 135. 142.]
   ...
   [ 82.  93.  99.]
   [ 82.  93.  99.]
   [ 83.  94. 100.]]

  [[115. 134. 141.]
   [116. 135. 142.]
   [116. 135. 142.]
   ...
   [ 77.  88.  94.]
   [ 75.  86.  92.]
   [ 76.  87.  93.]]

  ...

  [[ 39.  39.  37.]
   [ 36.  36.  34.]
   [ 35.  35.  33.]
   ...
   [ 42.  41.  39.]
   [ 45.  44.  42.]
   [ 43.  42.  40.]]

  [[ 38.  38.  36.]
   [ 37.  37.  35.]
   [ 36.  36.  34.]
   ...
   [ 45.  44.  42.]
   [ 43.  42.  40.]
   [ 34.  33.  31.]]

  [[ 33.  33.  31.]
   [ 33.  33.  31.]
   [ 32.  32.  30.]
   ...
   [ 43.  42.  40.]
   [ 34.  33.  31.]
   [ 20.  19.  17.]]]


 [[[ 30.  29.  24.]
   [ 21.  20.  15.]
   [ 19.  18.  13.]
   ...
   [ 17.  13.  10.]
   [ 16.  12.   9.]
   [ 15.  11.   8.]]

  [[ 26.  25.  20.]
   [ 19.  18.  13.]
   [ 17.  16.  11.]
   ...
   [ 16.  12.   9.]
 

In [8]:
print(a.shape)

(1646, 224, 224, 3)


In [9]:
import random

In [10]:
random.seed(5)
all_indices = [i for i in range(1646)]
train_indices = random.sample(range(1646), 1318)
print("Training Set Indices : ",len(train_indices))
valid_indices = [i for i in all_indices if i not in train_indices]
print("Validation Set Indices : ",len(valid_indices))

Training Set Indices :  1318
Validation Set Indices :  328


In [11]:
X_train = a[train_indices]
print(len(X_train))
print(X_train)

1318
[[[[ 11.  12.   7.]
   [ 21.  22.  17.]
   [ 17.  18.  13.]
   ...
   [ 11.  11.  11.]
   [ 11.  11.  11.]
   [ 19.  19.  19.]]

  [[  7.   8.   3.]
   [ 19.  20.  15.]
   [ 12.  13.   8.]
   ...
   [ 16.  16.  16.]
   [ 15.  15.  15.]
   [ 22.  22.  22.]]

  [[ 10.  11.   6.]
   [ 14.  15.  10.]
   [  6.   7.   2.]
   ...
   [ 13.  13.  13.]
   [ 12.  12.  12.]
   [ 17.  17.  17.]]

  ...

  [[ 65.  64.  62.]
   [ 66.  65.  63.]
   [ 62.  61.  59.]
   ...
   [ 94.  84.  74.]
   [ 95.  85.  75.]
   [ 96.  86.  76.]]

  [[ 61.  60.  58.]
   [ 69.  68.  66.]
   [ 63.  62.  60.]
   ...
   [ 93.  83.  73.]
   [ 95.  85.  75.]
   [ 96.  86.  76.]]

  [[ 59.  58.  56.]
   [ 72.  71.  69.]
   [ 64.  63.  61.]
   ...
   [ 92.  82.  72.]
   [ 94.  84.  74.]
   [ 95.  85.  75.]]]


 [[[223. 241. 255.]
   [138. 156. 170.]
   [140. 156. 171.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[203. 220. 236.]
   [154. 170. 185.]
   [159. 175. 190.]
   ...
   [255. 255. 25

In [12]:
X_valid = a[valid_indices]
len(X_valid)

328

In [13]:
print("X_train shape: ",X_train.shape)
print("X_valid shape: ",X_valid.shape)



X_train shape:  (1318, 224, 224, 3)
X_valid shape:  (328, 224, 224, 3)


In [14]:
path_to_train_labels = r'C:\Users\Aishwarya\Documents\GitHub\Emergency-Vehicle-Recognition\Python Notebook\Data\train\train_names_labels.csv'

df_train = pd.read_csv(path_to_train_labels)

In [15]:
df_train.head(3)

image_names  emergency_or_not
0            0                 1
1            1                 1
2            2                 1

In [16]:
all_labels = np.array(df_train['emergency_or_not'])

In [17]:
len(all_labels)

1646

In [18]:
y_train = all_labels[train_indices]
y_valid = all_labels[valid_indices]
print("y_train shape: ",y_train.shape)
print("y_valid shape: ",y_valid.shape)

y_train shape:  (1318,)
y_valid shape:  (328,)


In [19]:
print(a.shape)

(1646, 224, 224, 3)


In [20]:
from matplotlib.pyplot import imshow
%matplotlib inline

In [21]:
def identity_block(X, f, filters, stage, block):
    """
    Implementation of the identity block as defined in Figure 4
    
    Arguments:
    X -- input tensor of shape (m, n_H_prev, n_W_prev, n_C_prev)
    f -- integer, specifying the shape of the middle CONV's window for the main path
    filters -- python list of integers, defining the number of filters in the CONV layers of the main path
    stage -- integer, used to name the layers, depending on their position in the network
    block -- string/character, used to name the layers, depending on their position in the network
    
    Returns:
    X -- output of the identity block, tensor of shape (n_H, n_W, n_C)
    """
    
    # defining name basis
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'
    
    # Retrieve Filters
    F1, F2, F3 = filters
    
    # Save the input value. You'll need this later to add back to the main path. 
    X_shortcut = X
    
    # First component of main path
    X = Conv2D(filters = F1, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2a', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
    X = Activation('relu')(X)
    
   
    
    # Second component of main path 
    X = Conv2D(filters = F2, kernel_size = (f, f), strides = (1,1), padding = 'same', name = conv_name_base + '2b', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2b')(X)
    X = Activation('relu')(X)

    # Third component of main path 
    X = Conv2D(filters = F3, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2c', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)

    # Final step: Adding shortcut value to main path, and passing it through a RELU activation 
    X = Add()([X,X_shortcut])
    X = Activation('relu')(X)
    
    
    
    return X

In [22]:
def convolutional_block(X, f, filters, stage, block, s = 2):
    """
    Implementation of the convolutional block as defined in Figure 4
    
    Arguments:
    X -- input tensor of shape (m, n_H_prev, n_W_prev, n_C_prev)
    f -- integer, specifying the shape of the middle CONV's window for the main path
    filters -- python list of integers, defining the number of filters in the CONV layers of the main path
    stage -- integer, used to name the layers, depending on their position in the network
    block -- string/character, used to name the layers, depending on their position in the network
    s -- Integer, specifying the stride to be used
    
    Returns:
    X -- output of the convolutional block, tensor of shape (n_H, n_W, n_C)
    """
    
    # defining name basis
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'
    
    # Retrieve Filters
    F1, F2, F3 = filters
    
    # Save the input value
    X_shortcut = X


    # MAIN PATH
    # First component of main path 
    X = Conv2D(F1, (1, 1), strides = (s,s), name = conv_name_base + '2a',padding="valid", kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
    X = Activation('relu')(X)
    
    

    # Second component of main path 
    X = Conv2D(F2, (f, f), strides = (1,1), name = conv_name_base + '2b',padding="same", kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2b')(X)
    X = Activation('relu')(X)

    # Third component of main path 
    X = Conv2D(F3, (1, 1), strides = (1,1), name = conv_name_base + '2c',padding="valid", kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)

    #SHORTCUT PATH 
    X_shortcut = Conv2D(F3, (1, 1), strides = (s,s), name = conv_name_base + '1',padding="valid", kernel_initializer = glorot_uniform(seed=0))(X_shortcut)
    X_shortcut = BatchNormalization(axis = 3, name = bn_name_base + '1')(X_shortcut)

    # Final step: Adding shortcut value to main path, and passing it through a RELU activation 
    X = Add()([X_shortcut,X])
    X = Activation('relu')(X)
    
    
    
    return X

In [23]:
def ResNet50(input_shape = (64, 64, 3), classes = 6):
    """
    Implementation of the popular ResNet50 the following architecture:
    CONV2D -> BATCHNORM -> RELU -> MAXPOOL -> CONVBLOCK -> IDBLOCK*2 -> CONVBLOCK -> IDBLOCK*3
    -> CONVBLOCK -> IDBLOCK*5 -> CONVBLOCK -> IDBLOCK*2 -> AVGPOOL -> TOPLAYER

    Arguments:
    input_shape -- shape of the images of the dataset
    classes -- integer, number of classes

    Returns:
    model -- a Model() instance in Keras
    """
    
    # Define the input as a tensor with shape input_shape
    X_input = Input(input_shape)

    
    # Zero-Padding
    X = ZeroPadding2D((3, 3))(X_input)
    
    # Stage 1
    X = Conv2D(64, (7, 7), strides = (2, 2), name = 'conv1', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = 'bn_conv1')(X)
    X = Activation('relu')(X)
    X = MaxPooling2D((3, 3), strides=(2, 2))(X)

    # Stage 2
    X = convolutional_block(X, f = 3, filters = [64, 64, 256], stage = 2, block='a', s = 1)
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='b')
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='c')

    

    # Stage 3 (≈4 lines)
    X = convolutional_block(X, f = 3, filters = [128,128,512], stage = 3, block='a', s = 2)
    X = identity_block(X, 3, [128,128,512], stage=3, block='b')
    X = identity_block(X, 3, [128,128,512], stage=3, block='c')
    X = identity_block(X, 3, [128,128,512], stage=3, block='d')

    # Stage 4 (≈6 lines)
    X = convolutional_block(X, f = 3, filters = [256, 256, 1024], stage = 4, block='a', s = 2)
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='b')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='c')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='d')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='e')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='f')

    # Stage 5 (≈3 lines)
    X = convolutional_block(X, f = 3, filters = [512, 512, 2048], stage = 5, block='a', s = 2)
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='b')
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='c')

    # AVGPOOL (≈1 line). Use "X = AveragePooling2D(...)(X)"
    X = X = AveragePooling2D(pool_size=(2, 2),name="avg_pool")(X)
    
   

    # output layer
    X = Flatten()(X)
    X = Dense(classes, activation='softmax', name='fc' + str(classes), kernel_initializer = glorot_uniform(seed=0))(X)
    
    
    # Create model
    model = Model(inputs = X_input, outputs = X, name='ResNet50')

    return model

In [24]:
model = ResNet50(input_shape = (224, 224, 3), classes = 2)

In [25]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [26]:
def convert_to_one_hot(Y, C):
    Y = np.eye(C)[Y.reshape(-1)].T
    return Y

In [27]:
# Normalize image vectors
X_train = X_train/255.
X_valid = X_valid/255.
# Convert training and test labels to one hot matrices
y_train = convert_to_one_hot(y_train, 2).T
y_valid = convert_to_one_hot(y_valid, 2).T
print ("Number of training examples = " + str(a.shape[0]))
print ("X_train shape: " + str(X_train.shape))
print ("X_valid shape: " + str(X_valid.shape))
print ("y_train shape: " + str(y_train.shape))
print ("y_valid shape: " + str(y_valid.shape))

Number of training examples = 1646
X_train shape: (1318, 224, 224, 3)
X_valid shape: (328, 224, 224, 3)
y_train shape: (1318, 2)
y_valid shape: (328, 2)


In [28]:
model.fit(X_train, y_train, epochs = 12, batch_size = 10)


Epoch 1/12
1318/1318 [==============================] - 1716s 1s/step - loss: 3.2580 - accuracy: 0.5827
Epoch 2/12
1318/1318 [==============================] - 1790s 1s/step - loss: 1.2677 - accuracy: 0.6100
Epoch 3/12
1318/1318 [==============================] - 1982s 2s/step - loss: 0.9658 - accuracy: 0.5857
Epoch 4/12
1318/1318 [==============================] - 1968s 1s/step - loss: 0.6510 - accuracy: 0.6677
Epoch 5/12
1318/1318 [==============================] - 1902s 1s/step - loss: 0.5905 - accuracy: 0.7109
Epoch 6/12
1318/1318 [==============================] - 1969s 1s/step - loss: 0.5361 - accuracy: 0.7405
Epoch 7/12
1318/1318 [==============================] - 1663s 1s/step - loss: 0.5144 - accuracy: 0.7557
Epoch 8/12
1318/1318 [==============================] - 1451s 1s/step - loss: 0.4667 - accuracy: 0.7800
Epoch 9/12
1318/1318 [==============================] - 1406s 1s/step - loss: 0.4581 - accuracy: 0.8005
Epoch 10/12
1318/1318 [==============================] - 1379s 

In [ ]:
# In the following few lines of code, we will try to evaluate our trained model on validation data

In [29]:

preds = model.evaluate(X_valid, y_valid)
print (" Validation Set Loss = " + str(preds[0]))
print ("Validation Set Accuracy = " + str(preds[1]))

328/328 [==============================] - 133s 404ms/step
 Validation Set Loss = 0.5173940934785982
Validation Set Accuracy = 0.75
